characters = [
	{
		"name": "Mira Vale",
		"appearance": "Short black hair, mismatched boots, and a threadbare blue coat covered in odd stitched symbols",
		"job": "Cartographer",
		"order": "",
		"anomaly": True,
	},
	{
		"name": "Jonas Reed",
		"appearance": "Tall and broad-shouldered, with a tangled brown beard, soot-stained clothes, and one oversized glove",
		"job": "Blacksmith",
		"order": "",
		"anomaly": False,
	},
	{
		"name": "Elara Finch",
		"appearance": "Wild curly red hair, mismatched round glasses, and a coat patched with scraps of curtain fabric",
		"job": "Botanist",
		"order": "",
		"anomaly": True, 
        #hoi
	},
	{
		"name": "Theo Marsh",
		"appearance": "Thin and pale, wearing a stained yellow raincoat, three different socks, and a hat made from newspaper",
		"job": "Fisherman",
		"order": "",
		"anomaly": True,
	},
	{
		"name": "Sana Okafor",
		"appearance": "Dark braided hair, tired brown eyes, a frayed scarf, and a silver necklace made from bent spoons",
		"job": "Doctor",
		"order": "",
		"anomaly": False,
	},
	{
		"name": "Bram Hollow",
		"appearance": "Large build, shaved head, a scar over his eyebrow, and battered armor held together with rope",
		"job": "Guard",
		"order": "",
		"anomaly": False,
	},
	{
		"name": "Lydia Snow",
		"appearance": "Wild white hair, bright blue eyes, and an elegant purple dress repaired with colorful cloth scraps",
		"job": "Historian",
		"order": "",
		"anomaly": True,
	},
	{
		"name": "Kai Mercer",
		"appearance": "Messy blond hair, athletic build, worn sneakers, and a backpack patched with old maps",
		"job": "Courier",
		"order": "",
		"anomaly": False,
	},
	{
		"name": "Nora Bell",
		"appearance": "Medium height, warm smile, flour-dusted hair, and a green apron with pockets full of strange keys",
		"job": "Baker",
		"order": "",
		"anomaly": True,
	},
	{
		"name": "Orin Glass",
		"appearance": "Silver hair, narrow eyes, a black travel cloak with singed edges, and boots tied with wire",
		"job": "Alchemist",
		"order": "",
		"anomaly": True,
	},
	{
		"name": "Tessa Wright",
		"appearance": "Dark skin, shoulder-length curls, a patched green jacket, and sturdy work boots covered in dried mud",
		"job": "Engineer",
		"order": "",
		"anomaly": False,
	},
	{
		"name": "Felix Crow",
		"appearance": "Lean figure, oversized dark hood, crooked grin, and a coat lined with mismatched pockets",
		"job": "Detective",
		"order": "",
		"anomaly": True,
	},
	{
		"name": "Amara Stone",
		"appearance": "Muscular, with tangled long brown hair, a faded red scarf, and a coat patched with canvas bags",
		"job": "Miner",
		"order": "",
		"anomaly": False,
	},
	{
		"name": "Pavel North",
		"appearance": "Older man with a white mustache, a lopsided wool hat, and a raincoat repaired with fishing line",
		"job": "Lighthouse keeper",
		"order": "",
		"anomaly": True,
	},
	{
		"name": "Ivy Hart",
		"appearance": "Petite, with uneven violet hair, bright yellow boots, and a coat decorated with bottle caps",
		"job": "Musician",
		"order": "",
		"anomaly": True,
	},
	{
		"name": "Ronan Pike",
		"appearance": "Tanned skin, short dark hair, a salt-stained patched vest, and trousers held up with knotted rope",
		"job": "Sailor",
		"order": "",
		"anomaly": False,
	},
	{
		"name": "Mei Rowan",
		"appearance": "Long black hair, calm eyes, and a cream-colored robe patched with mismatched blankets",
		"job": "Teacher",
		"order": "",
		"anomaly": False,
	},
	{
		"name": "Gideon Frost",
		"appearance": "Very tall, with gray eyes, a heavy winter coat, and snow goggles hanging from a frayed string",
		"job": "Mountain guide",
		"order": "",
		"anomaly": True,
	},
	{
		"name": "Zara Bloom",
		"appearance": "Curly brown hair, colorful mismatched earrings, paint-stained hands, and a coat splashed with impossible colors",
		"job": "Artist",
		"order": "",
		"anomaly": True,
	},
	{
		"name": "Silas Quill",
		"appearance": "Thin and bespectacled, with a neatly trimmed mustache, a frayed cardigan, and shoes wrapped in cloth",
		"job": "Librarian",
		"order": "",
		"anomaly": False,
	},
]
